# Generated by Django 5.1.3 on 2024-12-31 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Account number must be 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(blank=True, default='Unknown Bank', max_length=100, null=True),
        ),
    ]
