# Generated by Django 5.1.3 on 2024-12-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
    ]
