# Generated by Django 5.1.3 on 2024-12-31 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_amount',
        ),
    ]
